spring.application.name=CoffeeShop

# Thông tin kết nối Firebase
firebase.database-url=https://coffeeshop-c0793-default-rtdb.asia-southeast1.firebasedatabase.app
firebase.config-path=classpath:coffeeshop-c0793-firebase-adminsdk-fbsvc-2571baa6f9.json

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Logging
logging.level.root=INFO
logging.level.com.example.CoffeeShop=DEBUG
